<a href="https://colab.research.google.com/github/nikhil2020/Mercedes-Benz-Greener-Manufacturing-Project/blob/master/Mercedes_Benz_Greener_Manufacturing_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Mercedes-Benz-Greener-Manufacturing-Project**


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
import time
import random
from math import * 
import operator 
import pandas as pd 
import numpy as np
# import plotting libraries
import matplotlib
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix 
%matplotlib inline
import seaborn as sns 
sns.set(style="white", color_codes=True) 
sns.set(font_scale=1.5)
# import the ML algorithm
import statsmodels.formula.api as smf
from sklearn.linear_model import LinearRegression #from pandas.core import datetools
# import libraries for model validation
from sklearn.model_selection import StratifiedKFold 
from sklearn.model_selection import cross_val_score 
from sklearn.model_selection import train_test_split
# import libraries for metrics and reporting
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 
from sklearn.metrics import accuracy_score
from sklearn import metrics
from statsmodels.tools.eval_measures import rmse 
import warnings
warnings.filterwarnings('ignore')


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [4]:
pwd

'/content'

In [5]:
import os
os.chdir("/content/drive/My Drive/Datasets/Mercedes-Benz-Greener-Manufacturing-Project")

In [6]:
 df = pd.read_csv('train.csv')

In [7]:
df.head()

ID       y  X0 X1  X2 X3 X4  ... X378 X379 X380  X382  X383  X384  X385
0   0  130.81   k  v  at  a  d  ...    0    0    0     0     0     0     0
1   6   88.53   k  t  av  e  d  ...    0    0    0     0     0     0     0
2   7   76.26  az  w   n  c  d  ...    0    0    0     1     0     0     0
3   9   80.62  az  t   n  f  d  ...    0    0    0     0     0     0     0
4  13   78.02  az  v   n  f  d  ...    0    0    0     0     0     0     0

[5 rows x 378 columns]

In [9]:
df.shape

(4209, 378)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [11]:
df.describe()

ID            y  ...         X384         X385
count  4209.000000  4209.000000  ...  4209.000000  4209.000000
mean   4205.960798   100.669318  ...     0.000475     0.001426
std    2437.608688    12.679381  ...     0.021796     0.037734
min       0.000000    72.110000  ...     0.000000     0.000000
25%    2095.000000    90.820000  ...     0.000000     0.000000
50%    4220.000000    99.150000  ...     0.000000     0.000000
75%    6314.000000   109.010000  ...     0.000000     0.000000
max    8417.000000   265.320000  ...     1.000000     1.000000

[8 rows x 370 columns]

In [12]:
df.columns

Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=378)

*Checking for the variance of all features and removing the feature which is equal to zero*

In [13]:
 df.var()==0

ID      False
y       False
X10     False
X11      True
X12     False
        ...  
X380    False
X382    False
X383    False
X384    False
X385    False
Length: 370, dtype: bool

### *Droping the feature whose variance is equal to zero*

In [14]:
 df.drop(['X11'],axis =1,inplace =True)

*Checking for null values*

In [15]:
 df.isnull().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 377, dtype: int64

*Count of the unique values in each feature*

In [16]:
 df.nunique().head(10)

ID    4209
y     2545
X0      47
X1      27
X2      44
X3       7
X4       4
X5      29
X6      12
X8      25
dtype: int64

***Coverting the dataset into independent and dependent variables***

In [17]:
 # Dependent variable
 y = df.iloc[:,1].values

In [19]:
# Independent variables
X = df.iloc[:,2:377].values

In [20]:
print(X.shape)
print(y.shape)

(4209, 375)
(4209,)


# ***Label Encoder***

Converting the nomial features object data types into numerical

In [22]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder 
encoder = LabelEncoder()
X[:,0] = encoder.fit_transform(X[:,0])
X[:,1] = encoder.fit_transform(X[:,1])
X[:,2] = encoder.fit_transform(X[:,2])
X[:,3] = encoder.fit_transform(X[:,3])
X[:,4] = encoder.fit_transform(X[:,4])
X[:,5] = encoder.fit_transform(X[:,5])
X[:,6] = encoder.fit_transform(X[:,6])
X[:,7] = encoder.fit_transform(X[:,7])

In [23]:
 X

array([[32, 23, 17, ..., 0, 0, 0],
       [32, 21, 19, ..., 0, 0, 0],
       [20, 24, 34, ..., 0, 0, 0],
       ...,
       [8, 23, 38, ..., 0, 0, 0],
       [9, 19, 25, ..., 0, 0, 0],
       [46, 19, 3, ..., 0, 0, 0]], dtype=object)

# ***PCA dimensionality reduction***

In [25]:
from sklearn.decomposition import PCA
X_centered = X - X.mean(axis=0)

In [26]:
pca = PCA(n_components=3)
pca.fit(X_centered)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [27]:
 X_pca = pca.transform(X_centered)

In [28]:
 X_pca.shape

(4209, 3)

In [29]:
 pca.components_

array([[-9.31138471e-01,  2.45494127e-01,  2.57713643e-01, ...,
         2.84628944e-06, -9.56497803e-06, -2.86842355e-05],
       [ 2.63046285e-01, -1.92186472e-02,  9.59720661e-01, ...,
        -9.23858305e-05, -5.16075133e-07, -1.32382564e-05],
       [ 1.40346165e-01,  5.51248020e-01,  2.15461586e-03, ...,
        -1.13659802e-04,  4.64816456e-05,  1.61546453e-04]])

In [30]:
 pca.explained_variance_

array([204.02462081, 113.83096499,  70.58204097])

In [31]:
 pca.explained_variance_ratio_

array([0.38334782, 0.21388033, 0.13261866])

# ***Splitting the dataset into traning and testing***

In [33]:
%time
# Splitting the dataset
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test = train_test_split(X_pca,y,test_size =0.3,random_state=1)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.48 µs


In [34]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2946, 3)
(1263, 3)
(2946,)
(1263,)


# ***Random Forest Regressor***

In [36]:
%time
# Importing the RF model from scikit learn ensemble 
from sklearn.ensemble import RandomForestRegressor 
classifier = RandomForestRegressor()
model = classifier.fit(X_train,y_train)
model

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.39 µs


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [37]:
# Predicting the values on independent variables testing dataset
y_pred = classifier.predict(X_test)

In [40]:
# Model evaluation metrics for regression
print('Mean Abs Error   MAE    : ', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Sq  Error MSE      : ', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Sq Error RMSE : ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('r2 value                : ', metrics.r2_score(y_test, y_pred))

Mean Abs Error   MAE    :  6.821459677866781
Mean Sq  Error MSE      :  92.23228040296354
Root Mean Sq Error RMSE :  9.603763866472537
r2 value                :  0.38454000233597485


# ***XGBoost Model Regressor***

In [42]:
%time
# Importing the XGBoost model from scikit learn ensemble 
from xgboost import XGBRegressor
classifier = XGBRegressor(n_estimator =1000) 
classifier.fit(X_train,y_train)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 22.2 µs
[10:51:01] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimator=1000,
             n_estimators=100, n_jobs=1, nthread=None, objective='reg:linear',
             random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=None, silent=None, subsample=1, verbosity=1)

In [43]:
 # Predicting the values on independent variables testing dataset
y_pred = classifier.predict(X_test)

In [45]:
# Model evaluation metrics for regression
print('Mean Abs Error   MAE    : ', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Sq  Error MSE      : ', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Sq Error RMSE : ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('r2 value                : ', metrics.r2_score(y_test, y_pred))

Mean Abs Error   MAE    :  7.5001429227827465
Mean Sq  Error MSE      :  98.57131012135072
Root Mean Sq Error RMSE :  9.92830852267146
r2 value                :  0.34224007004951906


### *The Champion model out of all Models is XGBoost*